{
 "createOrReplace": {
 "object": {
 "database": "Users"}, 
 "database": {
  "name": "Users",
  "id": "eb30e2ee-b0e7-4157-9ec4-4d9f11d38bf9",
  "compatibilityLevel": 1561,
  "createdTimestamp": "2021-02-13T04:30:58.41+05:30",
  "lastUpdate": "2023-03-14T14:13:36.003+05:30",
  "lastSchemaUpdate": "2022-09-14T02:32:37.603+05:30",
  "lastProcessed": "2023-03-14T14:13:35.953+05:30",
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "modifiedTime": "2023-03-14T08:43:27.983",
    "structureModifiedTime": "2023-03-14T08:43:27.983",
    "tables": [
      {
        "name": "Users",
        "lineageTag": "f4a36c4f-f1cc-40cf-a99e-ed162907a036",
        "modifiedTime": "2023-03-14T08:43:28.03",
        "structureModifiedTime": "2023-03-14T08:43:28.03",
        "columns": [
          {
            "type": "rowNumber",
            "name": "RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "modifiedTime": "2023-03-14T08:43:27.983",
            "structureModifiedTime": "2023-03-14T08:43:27.983",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2023-03-14T08:43:28.123",
              "refreshedTime": "2023-03-14T08:43:35.953"
            }
          },
          {
            "name": "FirstName",
            "dataType": "string",
            "sourceColumn": "FirstName",
            "lineageTag": "2b77dea3-0b14-46da-be0c-cd998ffcee22",
            "summarizeBy": "none",
            "modifiedTime": "2023-03-14T08:43:28.03",
            "structureModifiedTime": "2023-03-14T08:43:28.03",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2023-03-14T08:43:28.123",
              "refreshedTime": "2023-03-14T08:43:35.953"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2023-03-14T08:43:28.03"
              }
            ]
          },
          {
            "name": "LastName",
            "dataType": "string",
            "sourceColumn": "LastName",
            "lineageTag": "0cb4781e-edb5-49a4-bf90-c329df2e595d",
            "summarizeBy": "none",
            "modifiedTime": "2023-03-14T08:43:28.03",
            "structureModifiedTime": "2023-03-14T08:43:28.03",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2023-03-14T08:43:28.123",
              "refreshedTime": "2023-03-14T08:43:35.953"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2023-03-14T08:43:28.03"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "FullName",
            "dataType": "unknown",
            "isDataTypeInferred": true,
            "expression": "CONCATENATE(Users[FirstName],Users[LastName])"
          }
        ],
        "partitions": [
          {
            "name": "Users-dbd83a0f-30f6-436c-a895-d99f8d316230",
            "mode": "import",
            "state": "ready",
            "modifiedTime": "2023-03-14T08:43:35.953",
            "refreshedTime": "2023-03-14T08:43:35.953",
            "source": {
              "type": "m",
              "expression": "let\n  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WcswrzVLSUQotSEzJqEysTFSK1YlWCgYyc4Gi3onFJaVFmWCxkMS8xEqgmFdiZh5YwDkjMy83sVIBKOaRWFKSWp5YpBQbCwA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [FirstName = _t, LastName = _t]),\n  #\"Changed column type\" = Table.TransformColumnTypes(Source, {})\nin\n  #\"Changed column type\"\n"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2023-03-14T08:43:28.03"
          }
        ]
      },
      {
        "name": "DateTableTemplate_3ed62086-4927-44c9-a15f-fe4051c43b7e",
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "3bb62f6a-f9bd-44b5-997f-757baa0e1cf6",
        "modifiedTime": "2023-03-14T08:43:28.03",
        "structureModifiedTime": "2023-03-14T08:43:27.983",
        "columns": [
          {
            "type": "rowNumber",
            "name": "RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "modifiedTime": "2023-03-14T08:43:27.983",
            "structureModifiedTime": "2023-03-14T08:43:27.983",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2023-03-14T08:43:28.14",
              "refreshedTime": "2023-03-14T08:43:28.14"
            }
          },
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "formatString": "General Date",
            "lineageTag": "f7069a2d-4efb-4ecf-9efd-637c6285d7e0",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "modifiedTime": "2023-03-14T08:43:28.14",
            "structureModifiedTime": "2023-03-14T08:43:27.983",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2023-03-14T08:43:28.14",
              "refreshedTime": "2023-03-14T08:43:28.14"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2023-03-14T08:43:27.983"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR([Date])",
            "formatString": "0",
            "lineageTag": "c5192b6c-4eea-4a49-815d-48c51aaaa1de",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "modifiedTime": "2023-03-14T08:43:28.14",
            "structureModifiedTime": "2023-03-14T08:43:27.983",
            "refreshedTime": "2023-03-14T08:43:28.14",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2023-03-14T08:43:28.14",
              "refreshedTime": "2023-03-14T08:43:28.14"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2023-03-14T08:43:27.983"
              },
              {
                "name": "TemplateId",
                "value": "Year",
                "modifiedTime": "2023-03-14T08:43:27.983"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "MONTH([Date])",
            "formatString": "0",
            "lineageTag": "fbc6752d-1a4f-4ef6-9bf9-7c3386900dc7",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "modifiedTime": "2023-03-14T08:43:28.14",
            "structureModifiedTime": "2023-03-14T08:43:27.983",
            "refreshedTime": "2023-03-14T08:43:28.14",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2023-03-14T08:43:28.14",
              "refreshedTime": "2023-03-14T08:43:28.14"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2023-03-14T08:43:27.983"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber",
                "modifiedTime": "2023-03-14T08:43:27.983"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "e93eb95c-3196-4112-bfe0-e7964381f35d",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "modifiedTime": "2023-03-14T08:43:28.14",
            "structureModifiedTime": "2023-03-14T08:43:27.983",
            "refreshedTime": "2023-03-14T08:43:28.14",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2023-03-14T08:43:28.14",
              "refreshedTime": "2023-03-14T08:43:28.14"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2023-03-14T08:43:27.983"
              },
              {
                "name": "TemplateId",
                "value": "Month",
                "modifiedTime": "2023-03-14T08:43:27.983"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "lineageTag": "b0314d5e-2953-4938-83bb-095680c55f40",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "modifiedTime": "2023-03-14T08:43:28.14",
            "structureModifiedTime": "2023-03-14T08:43:27.983",
            "refreshedTime": "2023-03-14T08:43:28.14",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2023-03-14T08:43:28.14",
              "refreshedTime": "2023-03-14T08:43:28.14"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2023-03-14T08:43:27.983"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber",
                "modifiedTime": "2023-03-14T08:43:27.983"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "cf7a0e0b-e911-4bc0-a970-54a3909d7784",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "modifiedTime": "2023-03-14T08:43:28.153",
            "structureModifiedTime": "2023-03-14T08:43:27.983",
            "refreshedTime": "2023-03-14T08:43:28.153",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2023-03-14T08:43:28.153",
              "refreshedTime": "2023-03-14T08:43:28.153"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2023-03-14T08:43:27.983"
              },
              {
                "name": "TemplateId",
                "value": "Quarter",
                "modifiedTime": "2023-03-14T08:43:27.983"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "DAY([Date])",
            "formatString": "0",
            "lineageTag": "21112a23-7212-48c4-be50-d7aaf33aa37e",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "modifiedTime": "2023-03-14T08:43:28.14",
            "structureModifiedTime": "2023-03-14T08:43:27.983",
            "refreshedTime": "2023-03-14T08:43:28.14",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2023-03-14T08:43:28.14",
              "refreshedTime": "2023-03-14T08:43:28.14"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2023-03-14T08:43:27.983"
              },
              {
                "name": "TemplateId",
                "value": "Day",
                "modifiedTime": "2023-03-14T08:43:27.983"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DateTableTemplate_3ed62086-4927-44c9-a15f-fe4051c43b7e-7b122b28-008c-4d6b-bdf1-d65d2fbedfb1",
            "mode": "import",
            "state": "ready",
            "modifiedTime": "2023-03-14T08:43:28.14",
            "refreshedTime": "2023-03-14T08:43:28.14",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "d68bf54e-d977-4288-a63b-04ff67e4f989",
            "state": "ready",
            "modifiedTime": "2023-03-14T08:43:28.153",
            "structureModifiedTime": "2023-03-14T08:43:27.983",
            "refreshedTime": "2023-03-14T08:43:28.153",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "313d9b16-5397-43b7-8695-b1d90de12787",
                "modifiedTime": "2023-03-14T08:43:28.03"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "13b7f463-ccc7-400a-ae45-394663a6ff7f",
                "modifiedTime": "2023-03-14T08:43:28.03"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "22770347-c5a3-4ab9-b5a2-f49aca0b0850",
                "modifiedTime": "2023-03-14T08:43:28.03"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "927cfc08-d69d-461b-9945-7da8abee5656",
                "modifiedTime": "2023-03-14T08:43:28.03"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy",
                "modifiedTime": "2023-03-14T08:43:27.983"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true",
            "modifiedTime": "2023-03-14T08:43:27.983"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy",
            "modifiedTime": "2023-03-14T08:43:27.983"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Users\"]",
        "modifiedTime": "2023-03-14T08:43:27.983"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1",
        "modifiedTime": "2023-03-14T08:43:27.983"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.116.6874.5",
        "modifiedTime": "2023-03-14T08:43:28.03"
      }
    ]
  }
}
 }
 }